export const VALIDATION_LIMITS = {
  PROFILE_NAME_MAX: 60,
  PROFILE_CATEGORY_MAX: 30,
  PROFILE_CAPACITY_MIN: 1,
  PROFILE_CAPACITY_MAX: 100,
  ASSIGNMENT_TASK_MAX: 40,
  ASSIGNMENT_DEDICATION_MIN: 10,
  ASSIGNMENT_DEDICATION_MAX: 100,
} as const;

export const BOARD_DEFAULTS = {
  SLOT_COUNT_DEFAULT: 60,
  SLOT_WIDTH_DEFAULT: 48,
  SLOT_WIDTH_MIN: 30,
  SLOT_WIDTH_MAX: 110,
  SLOT_COUNT_MIN: 5,
  SLOT_COUNT_MAX: 120,
} as const;
